### ISSUE TITLE
Gem won't initialize with Rails 7.1

### ISSUE THREAD

**Issue by Floppy** [AaronLasseigne/sqlite3_ar_regexp#6]
Rails 7.0 was fine, but on upgrading to Rails 7.1, this error is thrown from this gem:

```
NoMethodError: undefined method `create_function' for {:adapter=>"sqlite3", :pool=>16, :timeout=>5000, :database=>"db/development.sqlite3"}:Hash (NoMethodError)

        connection.create_function('regexp', 2) do |func, pattern, expression|
                  ^^^^^^^^^^^^^^^^
/home/runner/work/van_dam/van_dam/vendor/bundle/ruby/3.2.0/gems/sqlite3_ar_regexp-2.2.0/lib/sqlite3_ar_regexp/extension.rb:14:in `initialize'
```

Looks like something must have been deprecated a while back and finally dropped?

**Comment by AaronLasseigne** [comment]
It looks like they've changed how the `initialize` function works: https://github.com/rails/rails/blob/v7.1.0/activerecord/lib/active_record/connection_adapters/abstract_adapter.rb#L128

The first argument used to be a connection but it's changing to a hash of connection information.

**Comment by AaronLasseigne** [comment]
Closed with version 3.0.0.

**Comment by AaronLasseigne** [comment]
Thanks for the PR!

**Comment by Floppy** [comment]
Fantastic, thanks for merging and releasing it!
